Added test harness
RoboTeamTwente/roboteam_input pull request #2
Opened 2016-09-29 11:26 UTC by bobismijnnaam

2016-09-29 11:26 UTC, review-ninja commented
<a href="https://app.review.ninja/RoboTeamTwente/roboteam_input/pull/2" target="_blank"><img src="https://app.review.ninja/68807230/pull/2/badge" alt="ReviewNinja"/>

2016-10-10 08:15 UTC, DennisdeW requested changes

2016-10-10 08:15 UTC, DennisdeW commented on src/joystick_input.h
> +int speedaxis=1;
Moeten dit globals zijn? Waarom geen members?

2016-10-10 08:15 UTC, DennisdeW commented on src/joystick_input.h
> +	Joy(ros::NodeHandle&);
Hier wordt eerst Joy::n geïnitialiseerd, en dan vervangen door de parameter. Gebruik liever initialiser lists:
`Joy(ros::NodeHandle& n) : n(n) {}`

2016-10-10 08:15 UTC, DennisdeW commented on src/joystick_input.cpp
> +
The code duplication is strong in this one.

2016-10-10 08:15 UTC, DennisdeW commented on src/joystick_input.cpp
> +    rtt::chatter1_pub = n.advertise<roboteam_msgs::RobotCommand>("robotcommands", 1000);
Kunnen deze niet ook in de constructor?

2016-10-10 08:39 UTC, DennisdeW commented on src/joystick_input.h
> +	Joy(ros::NodeHandle&);
Maar dan geen `{}`, maar de daadwerkelijke code.

2016-10-11 08:24 UTC, DennisdeW commented on src/joystick_input.h
> +	Joy(ros::NodeHandle n);
Dit lost het probleem nog niet op. Het moet `Joy(ros::NodeHandle& n) : n(n) {/*rest van ctor code*/}` zijn.

2016-10-26 13:45 UTC, DennisdeW approved these changes

2016-10-26 13:45 UTC, merged